import type { Metadata } from "next";
import PublicNavbar from "@/components/marketing/PublicNavbar";
import PublicFooter from "@/components/marketing/PublicFooter";
import DisclaimerBox from "@/components/marketing/DisclaimerBox";

export const metadata: Metadata = {
  title: "Modliq Legal Disclaimer — Decision Support & Pilot Terms",
  description: "Modliq legal disclaimer. The platform provides decision-support recommendations only. It does not guarantee production outcomes, regulatory compliance, buyer approval, or audit certification.",
  alternates: {
    canonical: "https://modliq-io.vercel.app/disclaimer",
  },
  openGraph: {
    title: "Modliq Legal Disclaimer — Decision Support & Pilot Terms",
    description: "Modliq provides decision-support recommendations based on user-provided data. It does not guarantee production outcomes or regulatory compliance.",
    url: "https://modliq-io.vercel.app/disclaimer",
    images: ["/og/modliq-og.png"],
  },
  twitter: {
    card: "summary_large_image",
    title: "Modliq Legal Disclaimer — Decision Support & Pilot Terms",
    description: "Modliq provides decision-support recommendations based on user-provided data. It does not guarantee production outcomes or regulatory compliance.",
    images: ["/og/modliq-og.png"],
  },
};

export default function DisclaimerPage() {
  return (
    <div className="bg-white text-slate-900 font-sans min-h-screen flex flex-col justify-between">
      <div>
        <PublicNavbar />
        <section className="py-16">
          <div className="max-w-4xl mx-auto px-4 sm:px-6 space-y-6">
            <h1 className="text-3xl font-extrabold text-[#1B2A4A]">Legal Disclaimer & Pilot Terms</h1>
            <div className="space-y-4 text-sm text-slate-600 leading-relaxed bg-[#F0F6FA] border border-[#D0E2F0] p-6 rounded-2xl">
              <p><strong>Modliq provides decision-support recommendations based on user-provided data.</strong> It does not guarantee production outcomes, regulatory compliance, buyer approval, or audit certification.</p>
              <p>All process settings and recommendations generated by Modliq ML or AI models must be validated through controlled engineering trials and qualified personnel review prior to implementation in live manufacturing environments.</p>
              <p>Quality Passports generated by Modliq present empirical dataset readiness, SPC control chart stability, and Cp/Cpk process capability summaries based strictly on input data. Quality Passports are informational reporting tools and do not constitute government, legal, ISO, or regulatory accreditation.</p>
              <p><strong>Free Launch Pilot Terms:</strong> Launch Pilot slots (limited to 10 qualified manufacturing companies upon application review) provide 14–30 day complimentary software access for process evaluation. Data remains private to the user organization.</p>
            </div>
            <DisclaimerBox />
          </div>
        </section>
      </div>
      <PublicFooter />
    </div>
  );
}