'use client';

import React, { useState } from 'react';
import Link from 'next/link';
import PublicNavbar from '@/components/layout/PublicNavbar';
import PublicFooter from '@/components/layout/PublicFooter';
import NoCodeWorkflowVisual from '@/components/marketing/NoCodeWorkflowVisual';
import NoCodeMeansSection from '@/components/marketing/NoCodeMeansSection';
import PlatformLayerVisual from '@/components/marketing/PlatformLayerVisual';
import InteractiveWorkflowTabs from '@/components/marketing/InteractiveWorkflowTabs';
import QualityPassportPreview from '@/components/marketing/QualityPassportPreview';
import AlgorithmTransparencyGrid from '@/components/marketing/AlgorithmTransparencyGrid';
import AutoMLComparisonTable from '@/components/marketing/AutoMLComparisonTable';
import RoiCalculatorWidget from '@/components/marketing/RoiCalculatorWidget';
import {
  Sparkles,
  ArrowRight,
  ShieldCheck,
  CheckCircle2,
  Activity,
  Target,
  Cpu,
  BarChart3,
  Truck,
  ChevronDown,
  Globe,
  SlidersHorizontal,
  Building2,
  Factory,
  Check,
  Award,
  ExternalLink,
  Info,
  Users,
  Code2,
  Database,
  UserCheck,
  X,
} from 'lucide-react';

export default function HomeClient() {
  const [activeFaq, setActiveFaq] = useState<number | null>(null);

  const toggleFaq = (index: number) => {
    setActiveFaq(activeFaq === index ? null : index);
  };

  const faqItems = [
    {
      q: 'Do I need a data scientist to use Modliq?',
      a: 'No. Modliq is designed for manufacturing teams that want to use machine learning and quality analytics without hiring a data scientist or ML engineer. The platform guides users through data upload, health checks, goal setup, optimization, validation, and reporting.',
    },
    {
      q: 'Do I need to know Python or advanced statistics?',
      a: 'No coding is required. Modliq explains dataset health, optimization setup, and quality metrics in a comfortable, guided interface. Process engineers and quality heads remain in full control of decisions.',
    },
    {
      q: 'Is Modliq a no-code ML platform?',
      a: 'Yes. Modliq allows manufacturing teams to use machine learning workflows without writing code. Users upload data, define goals in plain English, confirm variables and constraints visually, and run optimization through a guided interface.',
    },
    {
      q: 'Is Modliq the same as generic AutoML?',
      a: 'No. Generic AutoML platforms focus solely on model building for generic tables. Modliq focuses specifically on manufacturing decisions—combining dataset health, constrained optimization, SPC control charts, Cp/Cpk capability math, OEE, supplier lot traceability, trial SOPs, and buyer-ready Quality Passports.',
    },
    {
      q: 'Does Modliq replace engineers?',
      a: 'No. Modliq supports engineers with ML recommendations, quality validation math, and automated evidence documentation. Engineers remain in control and responsible for setup review and controlled trial validation.',
    },
    {
      q: 'What is Modliq?',
      a: 'Modliq is a no-code manufacturing intelligence and machine learning platform by Qeltrava AI. It helps factory teams turn production data into process decisions, validated quality, and buyer-ready Quality Passports.',
    },
    {
      q: 'What is a Quality Passport?',
      a: 'A Quality Passport is a buyer-ready report generated by Modliq that summarizes dataset readiness, process capability (Cpk), optimization trial discipline, supplier lot links, and SOP action plans into an audit-ready evidence document.',
    },
    {
      q: 'Who builds Modliq?',
      a: 'Modliq is designed, engineered, and maintained by Qeltrava AI for industrial manufacturing teams worldwide.',
    },
  ];

  return (
    <div className="min-h-screen w-full overflow-x-hidden bg-white text-[#1B2A4A] font-sans antialiased">
      {/* 1. Sticky Navbar */}
      <PublicNavbar />

      {/* 2. Hero Section — No Data Scientist Needed Positioning */}
      <section id="product" className="w-full bg-gradient-to-b from-[#F0F6FA] via-white to-white py-12 sm:py-20 border-b border-[#D0E2F0]">
        <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 space-y-10">
          
          {/* Headline & Badges */}
          <div className="text-center max-w-4xl mx-auto space-y-4">
            <div className="inline-flex flex-wrap items-center justify-center gap-2 px-3.5 py-1.5 bg-blue-50 border border-blue-200 rounded-full text-xs font-bold text-[#2B70AB]">
              <Globe className="w-3.5 h-3.5 text-[#2B70AB] shrink-0" />
              <span>Data Analyst + ML Engineer in One No-Code Manufacturing Platform</span>
            </div>

            <h1 className="text-3xl sm:text-5xl md:text-6xl font-extrabold text-[#1B2A4A] tracking-tight leading-[1.15]">
              Understand what happened. Optimize what happens next.
            </h1>

            <p className="text-base sm:text-lg md:text-xl text-slate-600 leading-relaxed max-w-3xl mx-auto font-medium">
              Modliq combines manufacturing analytics and no-code machine learning so factory teams can explore data, detect quality issues, optimize process settings, and generate buyer-ready reports — without hiring data analysts or ML engineers.
            </p>

            <p className="text-xs sm:text-sm text-[#2B70AB] font-bold">
              Built in Tamil Nadu by Qeltrava AI for manufacturers who want practical data intelligence without the complexity of a data team.
            </p>

            {/* CTAs */}
            <div className="pt-3 flex flex-wrap items-center justify-center gap-3 w-full">
              <Link
                href="/contact?interest=free-pilot"
                className="px-6 py-3.5 bg-[#2B70AB] hover:bg-[#1B2A4A] text-white rounded-xl text-xs sm:text-sm font-bold flex items-center justify-center gap-2 transition-all shadow-md hover:shadow-lg"
              >
                <Sparkles className="w-4 h-4 text-blue-200" /> Apply for Free Pilot
              </Link>
              <Link
                href="/login"
                className="px-6 py-3.5 bg-white hover:bg-[#F0F6FA] text-[#1B2A4A] border border-[#D0E2F0] rounded-xl text-xs sm:text-sm font-bold flex items-center justify-center gap-2 transition-all shadow-xs"
              >
                Launch Demo <ArrowRight className="w-4 h-4 text-[#2B70AB]" />
              </Link>
              <a
                href="#workflow"
                className="px-5 py-3.5 bg-[#F0F6FA] hover:bg-slate-200 text-[#1B2A4A] border border-[#D0E2F0] rounded-xl text-xs sm:text-sm font-semibold flex items-center justify-center transition-all"
              >
                See No-Code Workflow ↓
              </a>
            </div>
          </div>

          {/* Hero Visual: Interactive No-Code Workflow Preview */}
          <div id="workflow" className="pt-4 scroll-mt-24">
            <NoCodeWorkflowVisual />
          </div>
        </div>
      </section>

      {/* 3. Data Analyst + ML Engineer Mode Comparison Section */}
      <section className="w-full py-16 sm:py-24 bg-gradient-to-b from-white to-[#F0F6FA] border-b border-[#D0E2F0]">
        <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 space-y-16">
          <div className="text-center max-w-3xl mx-auto space-y-3">
            <span className="text-xs font-bold uppercase tracking-wider text-[#2B70AB] bg-blue-50 px-3.5 py-1 rounded-full border border-blue-200">
              Two Roles in One Platform
            </span>
            <h2 className="text-2xl sm:text-4xl font-extrabold text-[#1B2A4A] tracking-tight">
              Data Analyst + ML Engineer, built into one manufacturing platform.
            </h2>
            <p className="text-sm sm:text-base text-slate-600 leading-relaxed">
              Traditional teams need analysts to explain past performance and ML engineers to build future-facing optimization systems. Modliq brings both workflows into one guided no-code console.
            </p>
          </div>

          {/* Two-Column Mode Comparison Grid */}
          <div className="grid grid-cols-1 md:grid-cols-2 gap-8">
            {/* Column 1: Data Analyst Mode */}
            <div className="bg-white rounded-3xl border-2 border-blue-200 p-8 shadow-sm space-y-6 flex flex-col justify-between hover:shadow-md transition">
              <div className="space-y-4">
                <div className="flex items-center justify-between">
                  <span className="px-3 py-1 bg-blue-100 text-blue-900 font-extrabold text-xs rounded-full uppercase tracking-wider">
                    Backward-Looking Analytics
                  </span>
                  <BarChart3 className="w-6 h-6 text-[#2B70AB]" />
                </div>
                <div>
                  <h3 className="text-2xl font-extrabold text-[#1B2A4A]">1. Data Analyst Mode</h3>
                  <p className="text-sm font-bold text-[#2B70AB] mt-0.5">Analyze what happened</p>
                  <p className="text-xs text-slate-500 mt-1">Explore historical production and quality data.</p>
                </div>

                <div className="space-y-2 pt-2">
                  <h4 className="text-xs font-extrabold text-slate-700 uppercase tracking-wider">Core Capabilities</h4>
                  <ul className="space-y-1.5 text-xs text-slate-700">
                    <li className="flex items-center gap-2"><CheckCircle2 className="w-4 h-4 text-emerald-600 shrink-0" /> Clean and profile datasets</li>
                    <li className="flex items-center gap-2"><CheckCircle2 className="w-4 h-4 text-emerald-600 shrink-0" /> Detect missing values and duplicates</li>
                    <li className="flex items-center gap-2"><CheckCircle2 className="w-4 h-4 text-emerald-600 shrink-0" /> Run exploratory data analysis (EDA Studio)</li>
                    <li className="flex items-center gap-2"><CheckCircle2 className="w-4 h-4 text-emerald-600 shrink-0" /> Find trends, correlations, and outliers</li>
                    <li className="flex items-center gap-2"><CheckCircle2 className="w-4 h-4 text-emerald-600 shrink-0" /> Create SPC and Cp/Cpk quality reports</li>
                    <li className="flex items-center gap-2"><CheckCircle2 className="w-4 h-4 text-emerald-600 shrink-0" /> Analyze OEE and downtime Pareto</li>
                    <li className="flex items-center gap-2"><CheckCircle2 className="w-4 h-4 text-emerald-600 shrink-0" /> Compare suppliers, shifts, and machines</li>
                  </ul>
                </div>
              </div>

              <div className="pt-4 border-t border-slate-100 space-y-2">
                <span className="text-[11px] font-bold text-slate-400 uppercase tracking-wider block">Generated Analytics Outputs</span>
                <div className="flex flex-wrap gap-1.5">
                  {['Dataset Health Report', 'EDA Report', 'Quality Studio Summary', 'OEE Dashboard', 'Supplier Risk Report'].map((tag) => (
                    <span key={tag} className="px-2.5 py-1 bg-blue-50 text-[#2B70AB] text-[11px] font-bold rounded-lg border border-blue-100">
                      {tag}
                    </span>
                  ))}
                </div>
              </div>
            </div>

            {/* Column 2: ML Engineer Mode */}
            <div className="bg-white rounded-3xl border-2 border-purple-200 p-8 shadow-sm space-y-6 flex flex-col justify-between hover:shadow-md transition">
              <div className="space-y-4">
                <div className="flex items-center justify-between">
                  <span className="px-3 py-1 bg-purple-100 text-purple-900 font-extrabold text-xs rounded-full uppercase tracking-wider">
                    Forward-Looking Optimization
                  </span>
                  <Cpu className="w-6 h-6 text-purple-600" />
                </div>
                <div>
                  <h3 className="text-2xl font-extrabold text-[#1B2A4A]">2. ML Engineer Mode</h3>
                  <p className="text-sm font-bold text-purple-700 mt-0.5">Optimize what happens next</p>
                  <p className="text-xs text-slate-500 mt-1">Use machine learning to recommend better process decisions.</p>
                </div>

                <div className="space-y-2 pt-2">
                  <h4 className="text-xs font-extrabold text-slate-700 uppercase tracking-wider">Core Capabilities</h4>
                  <ul className="space-y-1.5 text-xs text-slate-700">
                    <li className="flex items-center gap-2"><CheckCircle2 className="w-4 h-4 text-purple-600 shrink-0" /> Parse natural language manufacturing goals</li>
                    <li className="flex items-center gap-2"><CheckCircle2 className="w-4 h-4 text-purple-600 shrink-0" /> Select target variables and controllable features</li>
                    <li className="flex items-center gap-2"><CheckCircle2 className="w-4 h-4 text-purple-600 shrink-0" /> Train predictive ML models (RandomForest, XGBoost)</li>
                    <li className="flex items-center gap-2"><CheckCircle2 className="w-4 h-4 text-purple-600 shrink-0" /> Calculate feature importance drivers</li>
                    <li className="flex items-center gap-2"><CheckCircle2 className="w-4 h-4 text-purple-600 shrink-0" /> Run constrained process optimization</li>
                    <li className="flex items-center gap-2"><CheckCircle2 className="w-4 h-4 text-purple-600 shrink-0" /> Recommend safe setpoints & trial ranges</li>
                    <li className="flex items-center gap-2"><CheckCircle2 className="w-4 h-4 text-purple-600 shrink-0" /> Monitor model confidence and drift</li>
                  </ul>
                </div>
              </div>

              <div className="pt-4 border-t border-slate-100 space-y-2">
                <span className="text-[11px] font-bold text-slate-400 uppercase tracking-wider block">Generated Machine Learning Outputs</span>
                <div className="flex flex-wrap gap-1.5">
                  {['Optimization Job', 'Recommended Setpoints', 'Safe Trial Range', 'Feature Importance', 'Trial SOP', 'Control Plan'].map((tag) => (
                    <span key={tag} className="px-2.5 py-1 bg-purple-50 text-purple-700 text-[11px] font-bold rounded-lg border border-purple-100">
                      {tag}
                    </span>
                  ))}
                </div>
              </div>
            </div>
          </div>

          {/* Bridge Section & Three-Panel Visual */}
          <div className="bg-white rounded-3xl border border-[#D0E2F0] p-8 sm:p-10 shadow-sm space-y-8">
            <div className="text-center max-w-2xl mx-auto space-y-2">
              <h3 className="text-xl sm:text-2xl font-extrabold text-[#1B2A4A]">Why factories need both.</h3>
              <p className="text-xs sm:text-sm text-slate-600 leading-relaxed">
                Knowing why yield dropped last month is useful. But manufacturing teams also need to know what settings to try next, how to validate them, and how to document the decision. Modliq connects backward-looking analysis with forward-looking machine learning recommendations.
              </p>
            </div>

            {/* Three-Panel Visual: Analyze -> Optimize -> Prove */}
            <div className="grid grid-cols-1 md:grid-cols-3 gap-6 pt-4">
              <div className="p-5 bg-blue-50/60 rounded-2xl border border-blue-200 space-y-2">
                <div className="flex items-center justify-between text-[#2B70AB]">
                  <span className="text-xs font-black uppercase tracking-wider">1. Analyze</span>
                  <BarChart3 size={18} />
                </div>
                <h4 className="text-sm font-bold text-slate-900">Historical Insights</h4>
                <p className="text-xs text-slate-600">Dataset Health, EDA Studio, SPC Control Charts, OEE, Supplier Risk Scorecard.</p>
              </div>

              <div className="p-5 bg-purple-50/60 rounded-2xl border border-purple-200 space-y-2">
                <div className="flex items-center justify-between text-purple-700">
                  <span className="text-xs font-black uppercase tracking-wider">2. Optimize</span>
                  <Cpu size={18} />
                </div>
                <h4 className="text-sm font-bold text-slate-900">Forward ML Predictions</h4>
                <p className="text-xs text-slate-600">Goal Parser, Predictive ML Model, Feature Drivers, Constrained Safe Ranges.</p>
              </div>

              <div className="p-5 bg-emerald-50/60 rounded-2xl border border-emerald-200 space-y-2">
                <div className="flex items-center justify-between text-emerald-700">
                  <span className="text-xs font-black uppercase tracking-wider">3. Prove</span>
                  <ShieldCheck size={18} />
                </div>
                <h4 className="text-sm font-bold text-slate-900">Quality Evidence</h4>
                <p className="text-xs text-slate-600">Trial SOP, CAPA Action Items, Quality Passport Certificate, Buyer Share Link.</p>
              </div>
            </div>
          </div>
        </div>
      </section>
      <section className="w-full py-16 sm:py-24 bg-white border-b border-[#D0E2F0]">
        <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 space-y-12">
          <div className="text-center max-w-3xl mx-auto space-y-3">
            <span className="text-xs font-bold uppercase tracking-wider text-[#2B70AB] bg-[#F0F6FA] px-3.5 py-1 rounded-full border border-[#D0E2F0]">
              The Manufacturing Data Barrier
            </span>
            <h2 className="text-2xl sm:text-4xl font-extrabold text-[#1B2A4A] tracking-tight">
              You should not need a data science team to improve factory decisions.
            </h2>
            <p className="text-sm sm:text-base text-slate-600 leading-relaxed">
              Most manufacturers already have useful data in Excel sheets, production logs, QC reports, databases, and batch records. But turning that data into optimization, quality insights, and buyer-ready evidence usually requires data scientists, ML engineers, consultants, or complex tools. Modliq removes that barrier. Your team can upload data, choose templates, write goals in plain English, review the setup, and run guided workflows without coding.
            </p>
          </div>

          <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-6">
            <div className="p-6 bg-[#F0F6FA] border border-[#D0E2F0] rounded-2xl space-y-3 hover:border-[#2B70AB] hover:shadow-md transition">
              <div className="w-10 h-10 bg-white rounded-xl border border-[#D0E2F0] flex items-center justify-center text-[#2B70AB]">
                <Users size={20} />
              </div>
              <h3 className="text-base font-bold text-[#1B2A4A]">No data science team required</h3>
              <p className="text-xs text-slate-600 leading-relaxed">
                Modliq guides users through dataset health, goal setup, optimization, and validation in a simple, comfortable workflow.
              </p>
            </div>

            <div className="p-6 bg-[#F0F6FA] border border-[#D0E2F0] rounded-2xl space-y-3 hover:border-[#2B70AB] hover:shadow-md transition">
              <div className="w-10 h-10 bg-white rounded-xl border border-[#D0E2F0] flex items-center justify-center text-[#2B70AB]">
                <Code2 size={20} />
              </div>
              <h3 className="text-base font-bold text-[#1B2A4A]">No ML engineering setup</h3>
              <p className="text-xs text-slate-600 leading-relaxed">
                No Python notebooks, model tuning, infrastructure setup, or custom data pipelines are required.
              </p>
            </div>

            <div className="p-6 bg-[#F0F6FA] border border-[#D0E2F0] rounded-2xl space-y-3 hover:border-[#2B70AB] hover:shadow-md transition">
              <div className="w-10 h-10 bg-white rounded-xl border border-[#D0E2F0] flex items-center justify-center text-[#2B70AB]">
                <Database size={20} />
              </div>
              <h3 className="text-base font-bold text-[#1B2A4A]">No complex BI implementation</h3>
              <p className="text-xs text-slate-600 leading-relaxed">
                Start with CSV or Excel. Connect Supabase/Postgres or MongoDB later when your team is ready.
              </p>
            </div>

            <div className="p-6 bg-[#F0F6FA] border border-[#D0E2F0] rounded-2xl space-y-3 hover:border-[#2B70AB] hover:shadow-md transition">
              <div className="w-10 h-10 bg-white rounded-xl border border-[#D0E2F0] flex items-center justify-center text-[#2B70AB]">
                <UserCheck size={20} />
              </div>
              <h3 className="text-base font-bold text-[#1B2A4A]">Engineers stay in control</h3>
              <p className="text-xs text-slate-600 leading-relaxed">
                Modliq asks users to confirm targets, variables, constraints, and safety before recommendations are generated.
              </p>
            </div>
          </div>
        </div>
      </section>

      {/* 4. Traditional Approach vs Modliq Approach Comparison */}
      <section className="w-full py-16 sm:py-24 bg-[#F0F6FA] border-b border-[#D0E2F0]">
        <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 space-y-10">
          <div className="text-center max-w-3xl mx-auto space-y-3">
            <span className="text-xs font-bold uppercase tracking-wider text-[#2B70AB] bg-white px-3.5 py-1 rounded-full border border-[#D0E2F0]">
              Workflow Paradigm Shift
            </span>
            <h2 className="text-2xl sm:text-4xl font-extrabold text-[#1B2A4A] tracking-tight">
              From expert-only workflows to guided manufacturing intelligence.
            </h2>
          </div>

          <div className="grid grid-cols-1 md:grid-cols-2 gap-8 max-w-5xl mx-auto">
            {/* Traditional Approach */}
            <div className="bg-white p-6 sm:p-8 rounded-3xl border-2 border-rose-200 shadow-sm space-y-4">
              <div className="flex items-center gap-2 mb-2">
                <span className="w-6 h-6 rounded-full bg-rose-100 text-rose-700 flex items-center justify-center font-bold text-xs">
                  <X size={14} className="stroke-[3]" />
                </span>
                <h3 className="font-bold text-rose-900 text-base">Traditional Expert-Only Approach</h3>
              </div>
              <ol className="space-y-2 text-xs text-slate-700">
                <li className="p-2.5 bg-rose-50/60 rounded-lg border border-rose-100">1. Hire expensive data scientists & ML engineers</li>
                <li className="p-2.5 bg-rose-50/60 rounded-lg border border-rose-100">2. Clean & profile messy factory data manually</li>
                <li className="p-2.5 bg-rose-50/60 rounded-lg border border-rose-100">3. Write custom Python notebooks & ML pipelines</li>
                <li className="p-2.5 bg-rose-50/60 rounded-lg border border-rose-100">4. Tune hyperparameters and debug algorithms</li>
                <li className="p-2.5 bg-rose-50/60 rounded-lg border border-rose-100">5. Interpret raw feature importances without domain rules</li>
                <li className="p-2.5 bg-rose-50/60 rounded-lg border border-rose-100">6. Manually format PDF reports and explain to plant teams</li>
              </ol>
            </div>

            {/* Modliq Approach */}
            <div className="bg-white p-6 sm:p-8 rounded-3xl border-2 border-[#2B70AB] shadow-md space-y-4">
              <div className="flex items-center gap-2 mb-2">
                <span className="w-6 h-6 rounded-full bg-blue-100 text-[#2B70AB] flex items-center justify-center font-bold text-xs">
                  <Check size={14} className="stroke-[3]" />
                </span>
                <h3 className="font-bold text-[#1B2A4A] text-base">Guided Modliq Approach</h3>
              </div>
              <ol className="space-y-2 text-xs text-slate-700">
                <li className="p-2.5 bg-blue-50/60 rounded-lg border border-blue-100 font-semibold text-[#1B2A4A]">1. Upload CSV/Excel or connect database</li>
                <li className="p-2.5 bg-blue-50/60 rounded-lg border border-blue-100 font-semibold text-[#1B2A4A]">2. Dataset readiness score & health warnings appear</li>
                <li className="p-2.5 bg-blue-50/60 rounded-lg border border-blue-100 font-semibold text-[#1B2A4A]">3. Type goal in plain English ("Maximize yield")</li>
                <li className="p-2.5 bg-blue-50/60 rounded-lg border border-blue-100 font-semibold text-[#1B2A4A]">4. Review & confirm variables and safety bounds</li>
                <li className="p-2.5 bg-blue-50/60 rounded-lg border border-blue-100 font-semibold text-[#1B2A4A]">5. Run optimization for safe setpoint windows</li>
                <li className="p-2.5 bg-blue-50/60 rounded-lg border border-blue-100 font-semibold text-[#1B2A4A]">6. Validate with Quality Studio & export Quality Passport</li>
              </ol>
            </div>
          </div>

          <div className="text-center pt-4">
            <span className="text-xs font-mono font-bold bg-[#1B2A4A] text-white px-5 py-2 rounded-full">
              Modliq makes manufacturing intelligence comfortable for factory teams — no code, no data science team, no ML engineering setup.
            </span>
          </div>
        </div>
      </section>

      {/* 5. No-Code Means Section */}
      <NoCodeMeansSection />

      {/* 6. Platform Layer Visual Stack */}
      <PlatformLayerVisual />

      {/* 7. Interactive Workflow Step Tabs */}
      <InteractiveWorkflowTabs />

      {/* 8. Quality Passport Showcase */}
      <QualityPassportPreview />

      {/* 9. Algorithm Transparency Grid */}
      <AlgorithmTransparencyGrid />

      {/* 10. Generic AutoML vs Modliq Comparison Table */}
      <AutoMLComparisonTable />

      {/* 11. Target Manufacturing Roles */}
      <section className="w-full py-16 sm:py-24 bg-[#F0F6FA] border-b border-[#D0E2F0]">
        <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 space-y-10">
          <div className="text-center max-w-3xl mx-auto space-y-3">
            <span className="text-xs font-bold text-[#2B70AB] uppercase tracking-wider bg-white px-3 py-1 rounded-full border border-[#D0E2F0]">
              Target Manufacturing Roles
            </span>
            <h2 className="text-2xl sm:text-4xl font-bold text-[#1B2A4A] tracking-tight">
              Built for manufacturing teams who need decisions, not just dashboards.
            </h2>
            <p className="text-sm text-slate-600">
              Modliq bridges plant operations and executive quality reporting through role-tailored no-code tools.
            </p>
          </div>

          <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-6">
            {[
              { role: 'Factory Owners', icon: <Building2 className="w-5 h-5 text-[#2B70AB]" />, desc: 'Clear visibility into line yields, plant OEE, monthly scrap reduction, and financial ROI estimates.' },
              { role: 'Plant Heads', icon: <Factory className="w-5 h-5 text-[#2B70AB]" />, desc: 'Cross-shift performance comparison, equipment downtime pareto, and unified operational control.' },
              { role: 'Quality Managers', icon: <ShieldCheck className="w-5 h-5 text-[#2B70AB]" />, desc: 'Automated SPC control charts, Cp/Cpk capability math, AQL sampling, and buyer-ready Quality Passports.' },
              { role: 'Process Engineers', icon: <SlidersHorizontal className="w-5 h-5 text-[#2B70AB]" />, desc: 'Dataset health validation, ML setpoint recommendations, and guided 7-batch trial SOPs.' },
              { role: 'Operations Managers', icon: <Activity className="w-5 h-5 text-[#2B70AB]" />, desc: 'Real-time OEE tracking (Avail × Perf × Qual), shift bottlenecks, and downtime root-cause analysis.' },
              { role: 'Supplier Quality Teams', icon: <Truck className="w-5 h-5 text-[#2B70AB]" />, desc: 'Material lot traceability, raw vendor defect correlation, and incoming lot risk scoring.' },
            ].map((aud, idx) => (
              <div key={idx} className="p-6 bg-white border border-[#D0E2F0] rounded-2xl space-y-3 shadow-xs hover:border-[#2B70AB] hover:shadow-md transition">
                <div className="w-10 h-10 bg-[#F0F6FA] rounded-xl border border-[#D0E2F0] flex items-center justify-center">
                  {aud.icon}
                </div>
                <h3 className="text-base font-bold text-[#1B2A4A]">{aud.role}</h3>
                <p className="text-xs text-slate-600 leading-relaxed">{aud.desc}</p>
              </div>
            ))}
          </div>
        </div>
      </section>

      {/* 12. Made in Tamil Nadu & Qeltrava AI Section */}
      <section className="w-full py-16 sm:py-24 bg-white border-b border-[#D0E2F0]">
        <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 space-y-8 text-center">
          <div className="inline-flex items-center gap-2 px-3 py-1 bg-[#F0F6FA] border border-[#D0E2F0] rounded-full text-xs font-bold text-[#2B70AB]">
            <Globe size={14} />
            <span>Built in Tamil Nadu, India</span>
          </div>

          <h2 className="text-2xl sm:text-4xl font-extrabold text-[#1B2A4A] tracking-tight max-w-3xl mx-auto">
            Made in Tamil Nadu. Built for manufacturing teams.
          </h2>

          <p className="text-sm sm:text-base text-slate-600 max-w-3xl mx-auto leading-relaxed">
            Tamil Nadu is home to Asia's premier automotive, textile, precision engineering, electronics, specialty chemical, food processing, and plastic manufacturing clusters. Modliq is architected with this practical, high-precision industrial context in mind.
          </p>

          <div className="p-6 bg-[#F0F6FA] border border-[#D0E2F0] rounded-2xl max-w-2xl mx-auto space-y-3">
            <span className="text-xs text-slate-500 font-medium block">
              Modliq is a flagship manufacturing intelligence product by
            </span>
            <h3 className="text-xl font-bold text-[#1B2A4A]">Qeltrava AI</h3>
            <div className="flex items-center justify-center gap-4 text-xs font-semibold pt-1">
              <a
                href="https://qeltravaai.vercel.app/en"
                target="_blank"
                rel="noopener noreferrer"
                className="text-[#2B70AB] hover:underline flex items-center gap-1"
              >
                Website <ExternalLink size={12} />
              </a>
              <a
                href="https://www.linkedin.com/company/qeltravai/"
                target="_blank"
                rel="noopener noreferrer"
                className="text-[#2B70AB] hover:underline flex items-center gap-1"
              >
                LinkedIn <ExternalLink size={12} />
              </a>
              <a
                href="https://www.instagram.com/qeltravaai"
                target="_blank"
                rel="noopener noreferrer"
                className="text-[#2B70AB] hover:underline flex items-center gap-1"
              >
                Instagram <ExternalLink size={12} />
              </a>
            </div>
          </div>
        </div>
      </section>

      {/* 13. Free Launch Pilot Selection Section */}
      <section className="w-full py-16 sm:py-24 bg-[#F0F6FA] border-b border-[#D0E2F0]">
        <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 space-y-10">
          <div className="text-center max-w-3xl mx-auto space-y-3">
            <span className="text-xs font-bold text-amber-800 bg-amber-100 px-3.5 py-1 rounded-full uppercase tracking-wider font-mono">
              10 Free Pilot Slots Available
            </span>
            <h2 className="text-2xl sm:text-4xl font-extrabold text-[#1B2A4A] tracking-tight">
              Free launch pilot for selected manufacturing companies.
            </h2>
            <p className="text-sm sm:text-base text-slate-600">
              We are selecting a small cohort of manufacturing teams to validate real plant workflows and refine Modliq with direct factory feedback.
            </p>
          </div>

          <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-4 gap-4 max-w-5xl mx-auto">
            <div className="p-5 bg-white rounded-2xl border border-[#D0E2F0] space-y-2">
              <span className="text-xs font-bold text-[#2B70AB] uppercase">Criterion 01</span>
              <h4 className="font-bold text-[#1B2A4A] text-sm">Real Production Data</h4>
              <p className="text-xs text-slate-600">You have historical CSV/Excel production or inspection logs.</p>
            </div>
            <div className="p-5 bg-white rounded-2xl border border-[#D0E2F0] space-y-2">
              <span className="text-xs font-bold text-[#2B70AB] uppercase">Criterion 02</span>
              <h4 className="font-bold text-[#1B2A4A] text-sm">Measurable Target</h4>
              <p className="text-xs text-slate-600">You have a clear yield, defect, scrap, or OEE problem to improve.</p>
            </div>
            <div className="p-5 bg-white rounded-2xl border border-[#D0E2F0] space-y-2">
              <span className="text-xs font-bold text-[#2B70AB] uppercase">Criterion 03</span>
              <h4 className="font-bold text-[#1B2A4A] text-sm">Controlled Trial Review</h4>
              <p className="text-xs text-slate-600">You can evaluate ML trial recommendations through controlled engineering review.</p>
            </div>
            <div className="p-5 bg-white rounded-2xl border border-[#D0E2F0] space-y-2">
              <span className="text-xs font-bold text-[#2B70AB] uppercase">Criterion 04</span>
              <h4 className="font-bold text-[#1B2A4A] text-sm">Pilot Feedback</h4>
              <p className="text-xs text-slate-600">You can share practical workflow feedback during the pilot period.</p>
            </div>
          </div>

          <div className="text-center pt-2">
            <Link
              href="/contact?interest=free-pilot"
              className="inline-flex items-center gap-2 px-8 py-3.5 bg-[#2B70AB] hover:bg-[#1B2A4A] text-white font-bold text-sm rounded-xl transition shadow-md"
            >
              <Sparkles size={16} /> Apply for Free Pilot
            </Link>
          </div>
        </div>
      </section>

      {/* 14. Interactive ROI Preview Widget */}
      <RoiCalculatorWidget />

      {/* 15. FAQ Section */}
      <section className="w-full py-16 sm:py-24 bg-white border-b border-[#D0E2F0]">
        <div className="max-w-4xl mx-auto px-4 sm:px-6 lg:px-8 space-y-8">
          <div className="text-center space-y-2">
            <span className="text-xs font-bold text-[#2B70AB] uppercase tracking-wider bg-[#F0F6FA] px-3.5 py-1 rounded-full border border-[#D0E2F0]">
              Frequently Asked Questions
            </span>
            <h2 className="text-2xl sm:text-3xl font-extrabold text-[#1B2A4A]">
              Questions about Modliq no-code ML & quality tools.
            </h2>
          </div>

          <div className="space-y-3">
            {faqItems.map((faq, idx) => (
              <div key={idx} className="p-4 sm:p-5 bg-[#F0F6FA] border border-[#D0E2F0] rounded-2xl space-y-2 shadow-xs">
                <button
                  onClick={() => toggleFaq(idx)}
                  className="w-full min-h-[44px] text-left font-bold text-xs sm:text-sm text-[#1B2A4A] flex items-center justify-between gap-2"
                >
                  <span>{faq.q}</span>
                  <ChevronDown className={`w-4 h-4 text-[#2B70AB] shrink-0 transition-transform ${activeFaq === idx ? 'rotate-180' : ''}`} />
                </button>
                {activeFaq === idx && (
                  <p className="text-xs text-slate-600 leading-relaxed pt-2 border-t border-[#D0E2F0]">
                    {faq.a}
                  </p>
                )}
              </div>
            ))}
          </div>
        </div>
      </section>

      {/* 16. Final High-Impact CTA Section */}
      <section className="py-16 sm:py-20 bg-gradient-to-r from-[#1B2A4A] to-[#2B70AB] text-white">
        <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 text-center space-y-6">
          <h2 className="text-2xl sm:text-4xl font-extrabold tracking-tight">
            Bring your factory data. Modliq will guide the workflow.
          </h2>
          <p className="text-blue-100 text-sm sm:text-base max-w-xl mx-auto leading-relaxed">
            Move from raw production logs to dataset readiness, ML optimization, quality validation, and buyer-ready Quality Passports — without writing code or hiring a data science team.
          </p>
          <div className="flex flex-wrap items-center justify-center gap-4 pt-2">
            <Link
              href="/contact?interest=free-pilot"
              className="px-6 py-3.5 bg-white text-[#1B2A4A] font-bold text-sm rounded-xl hover:bg-slate-100 transition shadow"
            >
              Apply for Free Pilot
            </Link>
            <Link
              href="/login"
              className="px-6 py-3.5 bg-[#2B70AB] text-white border border-white/30 font-bold text-sm rounded-xl hover:bg-blue-600 transition"
            >
              Launch Demo
            </Link>
            <Link
              href="/contact"
              className="px-6 py-3.5 bg-transparent text-white border border-white/40 font-semibold text-sm rounded-xl hover:bg-white/10 transition"
            >
              Contact Us
            </Link>
          </div>
        </div>
      </section>

      {/* Footer */}
      <PublicFooter />
    </div>
  );
}
