"use client";

import React, { useState } from "react";
import {
  X,
  Cpu,
  Download,
  CheckCircle2,
  Copy,
  Terminal,
  Zap,
  Box,
  FileCode,
} from "lucide-react";

interface OnnxExportModalProps {
  isOpen: boolean;
  onClose: () => void;
  modelName: string;
  algorithm: string;
}

export default function OnnxExportModal({
  isOpen,
  onClose,
  modelName,
  algorithm,
}: OnnxExportModalProps) {
  const [selectedFormat, setSelectedFormat] = useState<"onnx" | "cpp" | "python">("onnx");
  const [copied, setCopied] = useState(false);

  if (!isOpen) return null;

  const cppHeaderCode = `// Auto-generated by Modliq Edge Compiler v2.4
// Model: ${modelName} (${algorithm})
#ifndef MODLIQ_${modelName.toUpperCase()}_H
#define MODLIQ_${modelName.toUpperCase()}_H

#include <vector>
#include <cmath>

namespace modliq {
    struct Setpoints {
        float temperature_c;
        float pressure_kpa;
        float screw_rpm;
    };

    inline float predict_yield(const Setpoints& input) {
        // Optimized decision tree node evaluation (0.42ms latency)
        float score = 84.5f;
        if (input.temperature_c > 220.0f) score += 5.2f;
        if (input.pressure_kpa >= 430.0f && input.pressure_kpa <= 470.0f) score += 6.5f;
        return std::min(99.8f, score);
    }
}
#endif // MODLIQ_${modelName.toUpperCase()}_H`;

  const pythonScriptCode = `# Modliq Edge Python Inference Runtime
import onnxruntime as ort
import numpy as np

# Load ONNX binary runtime engine
session = ort.InferenceSession("${modelName}.onnx")
input_name = session.get_inputs()[0].name

def run_edge_inference(temp_c: float, pressure_kpa: float, rpm: float):
    features = np.array([[temp_c, pressure_kpa, rpm]], dtype=np.float32)
    result = session.run(None, {input_name: features})
    return float(result[0][0])

print("Edge Model Loaded. Testing sample:", run_edge_inference(230.0, 450.0, 120.0))`;

  const copyCode = () => {
    const code = selectedFormat === "cpp" ? cppHeaderCode : pythonScriptCode;
    navigator.clipboard.writeText(code);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center p-4 bg-slate-950/80 backdrop-blur-md animate-in fade-in">
      <div className="w-full max-w-3xl overflow-hidden rounded-2xl border border-slate-700/80 bg-[#0F172A] shadow-2xl shadow-cyan-950/50 flex flex-col">
        {/* Header */}
        <div className="flex items-center justify-between px-6 py-4 border-b border-slate-800 bg-slate-900/90">
          <div className="flex items-center gap-3">
            <div className="p-2 rounded-xl bg-cyan-500/20 text-cyan-400 border border-cyan-500/30">
              <Cpu size={22} />
            </div>
            <div>
              <h2 className="text-lg font-bold text-white tracking-tight flex items-center gap-2">
                Edge ONNX & C++ Header Compiler
                <span className="px-2 py-0.5 rounded text-[10px] font-mono bg-emerald-500/20 text-emerald-300 border border-emerald-500/30">
                  Sub-Millisecond PLC Edge
                </span>
              </h2>
              <p className="text-xs text-slate-400 font-mono">Target Model: {modelName}</p>
            </div>
          </div>
          <button
            onClick={onClose}
            className="p-1.5 rounded-lg text-slate-400 hover:text-white hover:bg-slate-800 transition-colors"
          >
            <X size={18} />
          </button>
        </div>

        {/* Format Selectors */}
        <div className="flex items-center justify-between px-6 py-3 border-b border-slate-800 bg-[#090D16]">
          <div className="flex items-center gap-2 font-mono">
            {[
              { id: "onnx", label: "ONNX Binary (.onnx)", icon: Box },
              { id: "cpp", label: "C++ Header (.h)", icon: FileCode },
              { id: "python", label: "Python Edge (.py)", icon: Terminal },
            ].map((fmt) => {
              const Icon = fmt.icon;
              const isActive = selectedFormat === fmt.id;
              return (
                <button
                  key={fmt.id}
                  onClick={() => setSelectedFormat(fmt.id as any)}
                  className={`flex items-center gap-2 px-3 py-1.5 rounded-lg text-xs font-semibold transition-all ${
                    isActive
                      ? "bg-cyan-500/20 text-cyan-300 border border-cyan-500/40 shadow-sm"
                      : "bg-slate-800/60 text-slate-400 border border-slate-700/50 hover:text-slate-200"
                  }`}
                >
                  <Icon size={14} />
                  {fmt.label}
                </button>
              );
            })}
          </div>

          <span className="text-xs text-emerald-400 font-mono font-semibold flex items-center gap-1">
            <Zap size={14} /> Latency Benchmark: 0.42 ms
          </span>
        </div>

        {/* Code / Download Body */}
        <div className="p-6 space-y-4">
          {selectedFormat === "onnx" ? (
            <div className="p-6 rounded-xl bg-slate-900 border border-slate-800 text-center space-y-4 font-mono">
              <div className="w-12 h-12 mx-auto rounded-full bg-cyan-500/20 text-cyan-400 flex items-center justify-center">
                <Box size={24} />
              </div>
              <div>
                <h3 className="text-sm font-bold text-white font-sans">Compiled ONNX v1.16 Model Binary</h3>
                <p className="text-xs text-slate-400 mt-1">
                  Ready for direct deployment on Siemens S7-1500, Beckhoff IPC, NVIDIA Jetson, or Raspberry Pi Edge Gateways.
                </p>
              </div>
              <div className="inline-flex items-center gap-4 text-xs text-slate-300 bg-slate-950 p-2.5 rounded-lg border border-slate-800">
                <span>File Size: <strong>1.42 MB</strong></span>
                <span>•</span>
                <span>Opset Version: <strong>18</strong></span>
                <span>•</span>
                <span>Quantization: <strong>FP16</strong></span>
              </div>
              <div>
                <a
                  href={`/api/v1/models/${modelName}/export-onnx`}
                  download={`${modelName}.onnx`}
                  className="inline-flex items-center gap-2 px-5 py-2.5 bg-gradient-to-r from-cyan-500 to-blue-600 hover:from-cyan-400 hover:to-blue-500 text-white font-sans text-xs font-bold rounded-xl shadow-lg shadow-cyan-950/50 transition-all"
                >
                  <Download size={16} />
                  Download {modelName}.onnx
                </a>
              </div>
            </div>
          ) : (
            <div className="space-y-2">
              <div className="flex items-center justify-between text-xs text-slate-400 font-mono">
                <span>Code Snippet ({selectedFormat === "cpp" ? "C++17 Header" : "Python 3.10 Runtime"})</span>
                <button
                  onClick={copyCode}
                  className="flex items-center gap-1 text-cyan-400 hover:text-cyan-300 transition-colors"
                >
                  {copied ? <CheckCircle2 size={14} className="text-emerald-400" /> : <Copy size={14} />}
                  {copied ? "Copied!" : "Copy Code"}
                </button>
              </div>
              <pre className="p-4 rounded-xl bg-slate-950 border border-slate-800 text-xs font-mono text-cyan-300 overflow-x-auto max-h-72">
                <code>{selectedFormat === "cpp" ? cppHeaderCode : pythonScriptCode}</code>
              </pre>
            </div>
          )}
        </div>

        {/* Footer */}
        <div className="px-6 py-3 border-t border-slate-800 bg-slate-900/90 flex items-center justify-between text-xs text-slate-400 font-mono">
          <span>Modliq Edge Compiler v2.4</span>
          <button
            onClick={onClose}
            className="px-4 py-1.5 rounded-lg bg-slate-800 text-slate-200 hover:bg-slate-700 transition-colors font-sans font-medium"
          >
            Close Compiler
          </button>
        </div>
      </div>
    </div>
  );
}
