import type { Metadata } from "next";
import PublicNavbar from "@/components/marketing/PublicNavbar";
import PublicFooter from "@/components/marketing/PublicFooter";

export const metadata: Metadata = {
  title: 'Modliq Terms of Service',
  description:
    'Modliq Terms of Service for manufacturing intelligence SaaS.',
  alternates: {
    canonical: 'https://modliq-io.vercel.app/terms',
  },
  openGraph: {
    title: 'Modliq Terms of Service',
    description:
      'Modliq Terms of Service for manufacturing intelligence SaaS.',
    url: 'https://modliq-io.vercel.app/terms',
    images: ['/og/modliq-og.png'],
  },
  twitter: {
    card: 'summary_large_image',
    title: 'Modliq Terms of Service',
    description:
      'Modliq Terms of Service for manufacturing intelligence SaaS.',
    images: ['/og/modliq-og.png'],
  },
};

export default function TermsPage() {
  return (
    <div className="bg-white text-slate-900 font-sans">
      <PublicNavbar />
      <section className="py-16">
        <div className="max-w-4xl mx-auto px-4 sm:px-6">
          <h1 className="text-3xl font-extrabold text-[#1B2A4A] mb-8">Terms of Service</h1>
          <div className="prose prose-sm text-slate-600 space-y-4">
            <p><strong>Last updated:</strong> {new Date().toLocaleDateString("en-IN", { year: "numeric", month: "long", day: "numeric" })}</p>
            <p>By using Modliq, you agree to these terms of service. If you do not agree, do not use the platform.</p>
            <h2 className="text-lg font-bold text-[#1B2A4A]">Acceptable Use</h2>
            <p>You may use Modliq for legitimate manufacturing data analysis, process optimization, and quality improvement. You may not use the platform for illegal purposes or to process data you do not have rights to.</p>
            <h2 className="text-lg font-bold text-[#1B2A4A]">AI Recommendations</h2>
            <p>Modliq provides decision-support recommendations based on user-provided data. It does not guarantee production outcomes, regulatory compliance, buyer approval, or audit certification. All process changes should be validated through controlled trials and responsible engineering review.</p>
            <h2 className="text-lg font-bold text-[#1B2A4A]">No Guarantee of Results</h2>
            <p>Modliq does not guarantee yield improvement, quality improvement, or any specific business outcome. Results depend on your data quality, process conditions, and how you apply the recommendations.</p>
            <h2 className="text-lg font-bold text-[#1B2A4A]">Payment and Cancellation</h2>
            <p>Paid plans are billed as described on the pricing page. You may cancel your subscription at any time. Refunds are subject to the terms of the specific plan.</p>
            <h2 className="text-lg font-bold text-[#1B2A4A]">Intellectual Property</h2>
            <p>You retain ownership of your data. Modliq retains ownership of the platform and its algorithms. Reports generated by Modliq are yours to use and share.</p>
            <h2 className="text-lg font-bold text-[#1B2A4A]">Limitation of Liability</h2>
            <p>To the maximum extent permitted by law, Modliq is not liable for any indirect, incidental, or consequential damages arising from the use of the platform.</p>
            <h2 className="text-lg font-bold text-[#1B2A4A]">Contact</h2>
            <p>For questions about these terms, email <a href="mailto:hello@modliq.io" className="text-[#2B70AB]">hello@modliq.io</a>.</p>
          </div>
        </div>
      </section>
      <PublicFooter />
    </div>
  );
}