import { Router, Request, Response } from 'express';
import { prisma } from '../lib/prisma';
import {
  DEFAULT_NAVBAR_CONFIG,
  DEFAULT_FOOTER_CONFIG,
  DEFAULT_SEO_CONFIG,
  DEFAULT_CHATBOT_CONFIG,
  DEFAULT_ANNOUNCEMENT_CONFIG,
  DEFAULT_CONTACT_CONFIG,
  DEFAULT_HOME_SECTIONS,
} from '../data/defaultWebsiteConfig';

const router = Router();

// GET /api/v1/public/website-config — Public website configuration (Public, no auth)
router.get('/website-config', async (req: Request, res: Response) => {
  try {
    const [settingsList, dbSections] = await Promise.all([
      prisma.websiteSettings.findMany(),
      prisma.homePageSection.findMany({ orderBy: { order: 'asc' } }),
    ]);

    const settingsMap: Record<string, any> = {};
    settingsList.forEach((item) => {
      try {
        settingsMap[item.key] = JSON.parse(item.valueJson);
      } catch {
        // Fallback if parse error
      }
    });

    const navbar = settingsMap.navbar || DEFAULT_NAVBAR_CONFIG;
    const footer = settingsMap.footer || DEFAULT_FOOTER_CONFIG;
    const seo = settingsMap.seo || DEFAULT_SEO_CONFIG;
    const chatbot = settingsMap.chatbot || DEFAULT_CHATBOT_CONFIG;
    const announcement = settingsMap.announcement || DEFAULT_ANNOUNCEMENT_CONFIG;
    const contact = settingsMap.contact || DEFAULT_CONTACT_CONFIG;

    let homeSections = dbSections.length > 0
      ? dbSections.map((sec) => ({
          sectionKey: sec.sectionKey,
          title: sec.title,
          subtitle: sec.subtitle,
          visible: sec.visible,
          order: sec.order,
          content: (() => {
            try {
              return JSON.parse(sec.contentJson);
            } catch {
              return {};
            }
          })(),
        }))
      : DEFAULT_HOME_SECTIONS.map((sec) => ({
          ...sec,
          content: JSON.parse(sec.contentJson),
        }));

    // Filter only public visible sections
    const visibleSections = homeSections.filter((s) => s.visible).sort((a, b) => a.order - b.order);

    res.json({
      success: true,
      data: {
        navbar,
        footer,
        seo,
        chatbot,
        announcement,
        contact,
        homeSections: visibleSections,
      },
    });
  } catch (error: any) {
    // Fail-safe default fallback
    res.json({
      success: true,
      data: {
        navbar: DEFAULT_NAVBAR_CONFIG,
        footer: DEFAULT_FOOTER_CONFIG,
        seo: DEFAULT_SEO_CONFIG,
        chatbot: DEFAULT_CHATBOT_CONFIG,
        announcement: DEFAULT_ANNOUNCEMENT_CONFIG,
        contact: DEFAULT_CONTACT_CONFIG,
        homeSections: DEFAULT_HOME_SECTIONS.filter((s) => s.visible),
      },
    });
  }
});

// POST /api/v1/public/chatbot — Public FAQ Assistant (Safe, no internal secrets)
router.post('/chatbot', async (req: Request, res: Response) => {
  try {
    const message = (req.body.message || '').trim().toLowerCase();

    let answer = "Modliq is a B2B SaaS manufacturing intelligence platform that helps plant engineers optimize process setpoints and generate certified Quality Passports. Contact our sales team for a custom demonstration.";
    let source = "faq";

    if (message.includes('free pilot') || message.includes('pilot')) {
      answer = "Our 30-day Free Pilot includes full access to process optimization, Quality Passport generation, and custom connector integration for up to 10 selected manufacturing plants.";
    } else if (message.includes('data') || message.includes('upload') || message.includes('format')) {
      answer = "Modliq supports CSV, Excel (XLSX), PDF batch logs, and direct database connectors (Postgres, Supabase, MongoDB, SQL Server).";
    } else if (message.includes('passport') || message.includes('quality passport')) {
      answer = "A Quality Passport is an immutable audit certificate generated by Modliq verifying batch compliance, process setpoint tolerances, and defect risk scores.";
    } else if (message.includes('pricing') || message.includes('cost')) {
      answer = "Modliq offers flexible tiering: Demo (Free), Pilot ($0 for 30 days), Pro ($1,499/mo), and Enterprise Dedicated. Visit /pricing or contact sales for details.";
    } else if (message.includes('data scientist') || message.includes('code')) {
      answer = "No data science or programming background is required! Modliq provides a zero-code AutoML interface designed for plant operators and quality engineers.";
    }

    res.json({
      success: true,
      answer,
      source,
    });
  } catch (error: any) {
    res.status(500).json({ success: false, error: 'Public chatbot unavailable' });
  }
});

// POST /api/v1/public/contact — Public Contact Form Submission
export const memoryContactLeads: any[] = [];

router.post('/contact', async (req: Request, res: Response) => {
  try {
    const { name, company, email, phone, city, industry, role, interest, message } = req.body || {};

    if (!name || !String(name).trim()) {
      return res.status(400).json({ success: false, error: 'Name is required.' });
    }

    if (!email || !String(email).trim()) {
      return res.status(400).json({ success: false, error: 'Email is required.' });
    }

    const leadData = {
      name: String(name).trim(),
      company: company ? String(company).trim() : null,
      email: String(email).trim(),
      phone: phone ? String(phone).trim() : null,
      city: city ? String(city).trim() : null,
      industry: industry ? String(industry).trim() : null,
      role: role ? String(role).trim() : null,
      interest: Array.isArray(interest) ? interest.join(', ') : (interest ? String(interest) : null),
      message: message ? String(message).trim() : null,
      status: 'NEW',
    };

    let leadId = `lead_${Date.now()}`;
    const memRecord = { id: leadId, ...leadData, createdAt: new Date().toISOString() };
    memoryContactLeads.unshift(memRecord);

    try {
      const created = await prisma.contactLead.create({
        data: leadData,
      });
      leadId = created.id;
    } catch (dbErr) {
      console.warn('[publicWebsite] DB lead save failed, using memory fallback:', (dbErr as any)?.message || dbErr);
    }

    return res.status(201).json({
      success: true,
      message: 'Thank you! Your contact message has been received.',
      id: leadId,
    });
  } catch (error: any) {
    console.error('Contact submission error:', error);
    return res.status(500).json({ success: false, error: 'Failed to submit contact form. Please try again.' });
  }
});

export default router;
