import React from 'react';

export default function StructuredData() {
  const siteUrl = process.env.NEXT_PUBLIC_SITE_URL || 'https://modliq-io.vercel.app';

  const jsonLdOrganization = {
    '@context': 'https://schema.org',
    '@type': 'Organization',
    name: 'Qeltrava AI',
    url: 'https://qeltravaai.vercel.app/en',
    logo: `${siteUrl}/logo.svg`,
    sameAs: [
      'https://www.linkedin.com/company/qeltravai/',
      'https://www.instagram.com/qeltravaai',
    ],
    address: {
      '@type': 'PostalAddress',
      addressRegion: 'Tamil Nadu',
      addressCountry: 'IN',
    },
  };

  const jsonLdSoftwareApp = {
    '@context': 'https://schema.org',
    '@type': 'SoftwareApplication',
    name: 'Modliq',
    applicationCategory: 'BusinessApplication',
    operatingSystem: 'Web',
    description:
      'Modliq is a manufacturing intelligence product by Qeltrava AI, built in Tamil Nadu, India. It connects data ingestion, health scoring, process optimization, Quality Studio, operations, supplier risk, and buyer-ready Quality Passports.',
    offers: {
      '@type': 'Offer',
      priceCurrency: 'INR',
      price: '0',
      description: 'Free launch pilot for the first 10 selected manufacturing companies.',
    },
    creator: {
      '@type': 'Organization',
      name: 'Qeltrava AI',
      url: 'https://qeltravaai.vercel.app/en',
    },
  };

  const jsonLdWebsite = {
    '@context': 'https://schema.org',
    '@type': 'WebSite',
    name: 'Modliq',
    url: siteUrl,
    description:
      'Modliq is a manufacturing intelligence product by Qeltrava AI, built in Tamil Nadu, India.',
    publisher: {
      '@type': 'Organization',
      name: 'Qeltrava AI',
    },
  };

  const jsonLdFaq = {
    '@context': 'https://schema.org',
    '@type': 'FAQPage',
    mainEntity: [
      {
        '@type': 'Question',
        name: 'What is Modliq?',
        acceptedAnswer: {
          '@type': 'Answer',
          text: 'Modliq is a manufacturing intelligence platform that helps factories turn production data into process optimization insights, quality validation, operations visibility, supplier risk analysis, and buyer-ready Quality Passports.',
        },
      },
      {
        '@type': 'Question',
        name: 'Who is Modliq for?',
        acceptedAnswer: {
          '@type': 'Answer',
          text: 'Modliq is built for manufacturing teams, plant heads, quality managers, process engineers, operations managers, supplier quality teams, and Indian MSME manufacturers.',
        },
      },
      {
        '@type': 'Question',
        name: 'Is Modliq made in India?',
        acceptedAnswer: {
          '@type': 'Answer',
          text: 'Yes. Modliq is a manufacturing intelligence product by Qeltrava AI, built in Tamil Nadu, India.',
        },
      },
      {
        '@type': 'Question',
        name: 'What is a Quality Passport?',
        acceptedAnswer: {
          '@type': 'Answer',
          text: 'A Quality Passport is a buyer-ready report generated by Modliq that summarizes dataset readiness, process capability, SPC stability, optimization discipline, supplier traceability, and improvement evidence.',
        },
      },
      {
        '@type': 'Question',
        name: 'Does Modliq replace engineers?',
        acceptedAnswer: {
          '@type': 'Answer',
          text: 'No. Modliq empowers process and quality engineers by automating statistical math and generating trial SOPs. Final process approval always remains with human engineering teams.',
        },
      },
      {
        '@type': 'Question',
        name: 'Can Modliq work with Excel or CSV?',
        acceptedAnswer: {
          '@type': 'Answer',
          text: 'Yes. Modliq supports universal data ingestion, including CSV/Excel file uploads, PDF/Word table extraction, and Supabase, Postgres, or MongoDB database connectors.',
        },
      },
      {
        '@type': 'Question',
        name: 'Does Modliq guarantee yield improvement?',
        acceptedAnswer: {
          '@type': 'Answer',
          text: 'Modliq provides machine learning surrogate model setpoint recommendations and financial ROI estimations based on historical plant data. Controlled trial validation is recommended.',
        },
      },
    ],
  };

  const jsonLdBreadcrumb = {
    '@context': 'https://schema.org',
    '@type': 'BreadcrumbList',
    itemListElement: [
      {
        '@type': 'ListItem',
        position: 1,
        name: 'Home',
        item: siteUrl,
      },
    ],
  };

  return (
    <>
      <script
        type="application/ld+json"
        dangerouslySetInnerHTML={{ __html: JSON.stringify(jsonLdOrganization) }}
      />
      <script
        type="application/ld+json"
        dangerouslySetInnerHTML={{ __html: JSON.stringify(jsonLdSoftwareApp) }}
      />
      <script
        type="application/ld+json"
        dangerouslySetInnerHTML={{ __html: JSON.stringify(jsonLdWebsite) }}
      />
      <script
        type="application/ld+json"
        dangerouslySetInnerHTML={{ __html: JSON.stringify(jsonLdFaq) }}
      />
      <script
        type="application/ld+json"
        dangerouslySetInnerHTML={{ __html: JSON.stringify(jsonLdBreadcrumb) }}
      />
    </>
  );
}
