"use client";

import React, { useState } from "react";
import {
  Cpu,
  Download,
  Copy,
  CheckCircle2,
  X,
  Terminal,
  FileCode,
  Box,
  Layers,
} from "lucide-react";

interface ONNXExporterProps {
  modelName?: string;
  version?: string;
  isOpen: boolean;
  onClose: () => void;
}

export default function ONNXExporterModal({
  modelName = "Extrusion_Thickness_Optimizer",
  version = "v2.1.0-prod",
  isOpen,
  onClose,
}: ONNXExporterProps) {
  const [activeTab, setActiveTab] = useState<"cpp" | "onnx" | "docker">("cpp");
  const [copied, setCopied] = useState(false);

  if (!isOpen) return null;

  const cppHeaderCode = `// Generated by Modliq Industrial Edge Compiler v2.4
// Target: Siemens S7-1500 PLC / Bosch Rexroth Industrial Gateway
// Model: ${modelName} (${version})
// Timestamp: 2026-07-27

#ifndef MODLIQ_MODEL_${modelName.toUpperCase()}_H
#define MODLIQ_MODEL_${modelName.toUpperCase()}_H

#include <vector>
#include <cmath>
#include <iostream>

namespace ModliqInference {

class IndustrialModelEngine {
public:
    IndustrialModelEngine() {
        // Initialize XGBoost decision tree weight matrix
        weights_ = { 0.4201f, 0.2814f, 0.1802f, 0.1245f };
        bias_ = 0.042f;
    }

    float predict(const std::vector<float>& features) {
        if (features.size() < 4) return -1.0f;
        float score = bias_;
        for (size_t i = 0; i < features.size() && i < weights_.size(); ++i) {
            score += features[i] * weights_[i];
        }
        return 1.0f / (1.0f + std::exp(-score)); // Sigmoid yield probability
    }

private:
    std::vector<float> weights_;
    float bias_;
};

} // namespace ModliqInference

#endif // MODLIQ_MODEL_${modelName.toUpperCase()}_H
`;

  const dockerfileCode = `# Modliq Industrial Edge Runtime Container
FROM alpine:3.19
RUN apk add --no-libc-dev g++ make onnxruntime-dev
COPY model_artifacts.onnx /edge/model.onnx
COPY main.cpp /edge/main.cpp
WORKDIR /edge
RUN g++ -O3 -o modliq_edge_engine main.cpp -lonnxruntime
CMD ["./modliq_edge_engine", "--port=50051"]
`;

  const getActiveCode = () => {
    if (activeTab === "cpp") return cppHeaderCode;
    if (activeTab === "docker") return dockerfileCode;
    return `{"model_name": "${modelName}", "version": "${version}", "format": "ONNX_v1.15", "input_shape": [1, 4], "output_shape": [1, 1]}`;
  };

  const handleCopy = () => {
    navigator.clipboard.writeText(getActiveCode());
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center p-4 bg-slate-950/80 backdrop-blur-md animate-in fade-in">
      <div className="w-full max-w-3xl overflow-hidden rounded-xl border border-white/10 bg-[#0F172A] shadow-2xl text-slate-100 font-sans">
        {/* Header */}
        <div className="flex items-center justify-between px-6 py-4 border-b border-white/10 bg-slate-900/80">
          <div className="flex items-center space-x-3">
            <div className="p-2 rounded-lg bg-cyan-500/10 border border-cyan-500/30 text-cyan-400">
              <Cpu className="w-5 h-5" />
            </div>
            <div>
              <h3 className="text-lg font-bold text-white tracking-tight">
                1-Click ONNX Edge C++ Code Generator
              </h3>
              <p className="text-xs text-slate-400 font-mono">
                Siemens S7 PLC, Bosch Rexroth, and Industrial Edge C++ headers
              </p>
            </div>
          </div>
          <button onClick={onClose} className="p-1 rounded-lg text-slate-400 hover:text-white hover:bg-white/10">
            <X className="w-5 h-5" />
          </button>
        </div>

        {/* Tab Switcher */}
        <div className="flex items-center space-x-2 px-6 pt-4 border-b border-white/10 bg-slate-950 font-mono text-xs">
          <button
            onClick={() => setActiveTab("cpp")}
            className={`px-4 py-2 border-b-2 font-bold transition-all flex items-center space-x-1.5 ${
              activeTab === "cpp"
                ? "border-cyan-400 text-cyan-300 bg-cyan-500/10"
                : "border-transparent text-slate-400 hover:text-slate-200"
            }`}
          >
            <FileCode className="w-4 h-4" />
            <span>C++ PLC Header (.h)</span>
          </button>
          <button
            onClick={() => setActiveTab("onnx")}
            className={`px-4 py-2 border-b-2 font-bold transition-all flex items-center space-x-1.5 ${
              activeTab === "onnx"
                ? "border-cyan-400 text-cyan-300 bg-cyan-500/10"
                : "border-transparent text-slate-400 hover:text-slate-200"
            }`}
          >
            <Box className="w-4 h-4" />
            <span>ONNX Runtime Manifest</span>
          </button>
          <button
            onClick={() => setActiveTab("docker")}
            className={`px-4 py-2 border-b-2 font-bold transition-all flex items-center space-x-1.5 ${
              activeTab === "docker"
                ? "border-cyan-400 text-cyan-300 bg-cyan-500/10"
                : "border-transparent text-slate-400 hover:text-slate-200"
            }`}
          >
            <Layers className="w-4 h-4" />
            <span>Edge Dockerfile</span>
          </button>
        </div>

        {/* Code View */}
        <div className="p-6 max-h-[50vh] overflow-y-auto font-mono text-xs bg-slate-950">
          <pre className="p-4 rounded-xl bg-slate-900 border border-white/10 text-cyan-300 leading-relaxed overflow-x-auto">
            <code>{getActiveCode()}</code>
          </pre>
        </div>

        {/* Footer Actions */}
        <div className="flex items-center justify-between px-6 py-4 border-t border-white/10 bg-slate-900/80 font-mono text-xs">
          <span className="text-slate-400">Target Latency: <strong className="text-emerald-400">4.2ms</strong> (Zero Cloud Latency)</span>
          <div className="flex items-center space-x-3">
            <button
              onClick={handleCopy}
              className="px-3.5 py-2 rounded-lg border border-white/10 bg-slate-800 hover:bg-slate-700 text-slate-200 font-bold flex items-center space-x-1.5 transition-all"
            >
              {copied ? <CheckCircle2 className="w-4 h-4 text-emerald-400" /> : <Copy className="w-4 h-4" />}
              <span>{copied ? "Copied!" : "Copy Code"}</span>
            </button>
            <button
              onClick={() => alert(`Downloading ${activeTab.toUpperCase()} bundle for ${modelName}...`)}
              className="px-4 py-2 rounded-lg bg-cyan-500 hover:bg-cyan-400 text-slate-950 font-bold flex items-center space-x-2 transition-all shadow-lg shadow-cyan-500/20"
            >
              <Download className="w-4 h-4" />
              <span>Download Edge Package</span>
            </button>
          </div>
        </div>
      </div>
    </div>
  );
}
