import os
import json

docs_dir = r"c:\Users\sathish\Desktop\Modliq\Modliq\docs"
output_file = r"c:\Users\sathish\Desktop\Modliq\Modliq\frontend\src\lib\docsData.ts"

categories = [
    {"id": "index", "title": "Index & Overview", "icon": "BookOpen"},
    {"id": "00-overview", "title": "00 Product Overview", "icon": "Info"},
    {"id": "01-architecture", "title": "01 System Architecture", "icon": "Layers"},
    {"id": "02-frontend", "title": "02 Frontend Architecture", "icon": "Layout"},
    {"id": "03-backend", "title": "03 Backend Gateway", "icon": "Server"},
    {"id": "04-ml-engine", "title": "04 ML Engine", "icon": "Cpu"},
    {"id": "05-database", "title": "05 Database & Schema", "icon": "Database"},
    {"id": "06-ai", "title": "06 AI Gateway", "icon": "Brain"},
    {"id": "07-security", "title": "07 Security & Compliance", "icon": "Shield"},
    {"id": "08-deployment", "title": "08 Deployment & Cloud", "icon": "Cloud"},
    {"id": "09-testing", "title": "09 Testing & QA", "icon": "CheckSquare"},
    {"id": "10-launch", "title": "10 Launch Readiness", "icon": "Rocket"},
    {"id": "11-developer-onboarding", "title": "11 Developer Onboarding", "icon": "Terminal"},
    {"id": "archive", "title": "Archive & Legacy", "icon": "Archive"},
]

docs_map = {}

for root, _, files in os.walk(docs_dir):
    for f in files:
        if f.endswith('.md'):
            full_path = os.path.join(root, f)
            rel_path = os.path.relpath(full_path, docs_dir).replace('\\', '/')
            with open(full_path, 'r', encoding='utf-8') as file:
                content = file.read()
            
            # Derive title
            title = f.replace('.md', '').replace('_', ' ')
            lines = content.split('\n')
            for line in lines[:5]:
                if line.startswith('# '):
                    title = line.replace('# ', '').strip()
                    break
            
            # Determine category
            category = "index"
            parts = rel_path.split('/')
            if len(parts) > 1:
                category = parts[0]
            
            slug = rel_path.replace('.md', '').lower()
            
            docs_map[slug] = {
                "relPath": rel_path,
                "title": title,
                "category": category,
                "filename": f,
                "content": content
            }

ts_content = f"""// Auto-generated by scripts/generate_docs_data.py
// Total files: {len(docs_map)}

export interface DocItem {{
  relPath: string;
  title: string;
  category: string;
  filename: string;
  content: string;
}}

export interface CategoryInfo {{
  id: string;
  title: string;
  icon: string;
}}

export const DOC_CATEGORIES: CategoryInfo[] = {json.dumps(categories, indent=2)};

export const DOCS_DATA: Record<string, DocItem> = {json.dumps(docs_map, indent=2)};
"""

with open(output_file, 'w', encoding='utf-8') as f:
    f.write(ts_content)

print(f"Successfully generated {output_file} with {len(docs_map)} documents.")
